//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Pedido
    {
        public int idDetalle { get; set; }
        public int idPedido { get; set; }
        public int idLicor { get; set; }
        public int iPrecio { get; set; }
        public int iCantidad { get; set; }
    
        public virtual Licores Licores { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
